twig:
    file_name_pattern: "*.twig"

    debug: true # true en dev, false en prod
    strict_variables: true # true en dev, false en prod
    cache: false # false en dev, true en prod

    form_themes:
        - "form/_theme.html.twig"

when@test:
    twig:
        strict_variables: true
